### ISSUE TITLE
How to make the second page take up full width?

### ISSUE THREAD

**Issue by RashiqAzhan** [mateuszbaransanok/BubbleCV#10]
I currently have a huge empty space on the right. Is it possible to finish the second column on the first page?

Thank you for you work.

**Comment by mateuszbaransanok** [comment]
Hello, I glad you use my template. If you want to end a double column layout, you can easily do so by placing `\cvevents` outside the `cv` block:

```
\begin{cv}
<main column>
\cvsidebar
<side column>
\end{cv}
<main column (full line width)>  <- put your events here
\end{document}
```

PS. However, I personally do not recommend a two-page CV. Recruiters don't like them very much. If I were you, I would use `\cvscale` to fit everything on one page.
