### ISSUE TITLE
Allow left column to stretch to the right (if no content in second column)

### ISSUE THREAD

**Issue by luciusf** [mateuszbaransanok/BubbleCV#11]
Hi there - great CV template - thank you!

I have one problem with it though, and I assume a change isn't feasible atm, because of the layout being "just" two columns. 

But, 
currently, if there isn't much content for the right column but more for the left one, it's potentially stretching the CV over much more pages than necessary, while leaving an awful lot of space wasted (empty second column on the right). 

Maybe there could be a way (a flag), to limit the second (right) column to the first page, while having the following pages (2+) only show the first column but with full width?

**Comment by mateuszbaransanok** [comment]
Hi, I am glad you liked my template.

Checkout this issue https://github.com/mateuszbaransanok/BubbleCV/issues/10#issuecomment-2140551105 I think that should help you ;)

**Comment by luciusf** [comment]
Thank you for your quick reply! I failed to search through closed issues, sorry

I tested the added `\cvevent` after the `cv` block, and it worked!!

(edit: I am just realizing, that the fonts outside `cv` are different, so not consistent throughout the document)

I didn't really get your `\cvscale` suggestion however. It's not listed in the functions of the [README.md](https://github.com/mateuszbaransanok/BubbleCV/tree/main#functions), and looking through the [commit](https://github.com/mateuszbaransanok/BubbleCV/commit/05f646ac08519d06047ab91d4c9c6308683b8bcc) which I guess introduced it, I couldn't quickly(!) grasp what it's supposed to do. 

If it's just, well, scaling, than I don't think it would solve empty space distribution in my case, since the right column is just on the first page, but the work experiences, stretches to page 3 - something I'd like to bring down to 2. I don't think mere scaling would help as much here. But maybe I just need to understand `\cvscale`. 

Lastly - if there is anything you can share - I'd be interested to know, how you know that recruiters don't like this style.

**Comment by mateuszbaransanok** [comment]
You're right, the text is different, I didn't notice it before. Thanks for noticing this!

You can simply fix it by adding
```
\relscale{\cvscale}%
\fontfamily{\cvfont}%
```
before the text outside the `cv` block (after `\end{cv}`).

`\cvscale` is used to manipulate the size of text and other CV elements to fit content to a page. If there is too little or too much text (several lines go to the next page), you can scale text to fit a page.

This won't work in your case. You have two whole pages of text, so scaling won't help you.

Honestly, in my opinion, recruiters are usually lazy :) they don't like to read too much, so your CV should be concise and contain only information relevant to a given position or something that makes an impression ;) .

This doesn't mean your CV has to be one-sided. It also depends on your professional experience, education and the company to which you are sending your CV. This is very personal so I'm sure your judgment is the correct one.

I'll try to find a solution to simplify end a two-column block with a specific command. I will also add information about scaling and other parameters in the style file to the README.

**Comment by luciusf** [comment]
Thank you for the follow up! The `\fontfamily{\cvfont}%` did indeed do the trick, and I am ready to go!

My SO used to work in recruiting back in the days, and she ok'ed the version, where the second column isn't used on page 2+, so I was just wondering if I'd miss an important trend or so :). Thank you for your additional comments. 

A couple of my CV reviewers mentioned, they'd strongly prefer sans-serif. Since your template put's everything so neatly in the sty and has good documentation, I thought you might want to add a note about changing the fontfamily to the README. I played around with it, but always ended up with unsatisfying results that weren't visually pleasing. Just sharing - not an issue. 

In any way - thank you again for your quick follow-ups!!
