### ISSUE TITLE
Non-circular Avatar

### ISSUE THREAD

**Issue by eyildiz-ugoe** [mateuszbaransanok/BubbleCV#12]
Hey, nice template!

I was wondering if it is possible to use the avatar image as is, without having it in a circular format? If so, could you let me know? I see `/drawcircle` command, should they be removed in this case? Could you perhaps provide some help regarding that code section? 

Thanks in advance!

**Comment by mateuszbaransanok** [comment]
Hi, I thought it would be pretty easy, but unfortunately there was a problem when rendering the PDF. 

I have a workaround

```
\NewDocumentEnvironment{cv}{O{} O{2} m m}{%
    \relscale{\cvscale}%
    \fontfamily{\cvfont}%
    
    \vspace*{\cvheadermargin mm}%
    \vspace*{-\cvtopmargin mm}%
    \hspace{-\timelinespace mm}%
    \hspace{-\cvavatarradius mm}%
    \begin{minipage}{\dimexpr(\cvavatarradius mm + \cvavatarradius mm)}%
        \includegraphics[width=#2\dimexpr\cvavatarradius mm\relax, height=#2\dimexpr\cvavatarradius mm\relax]{resources/#1}%  <- HERE
    \end{minipage}%
    \hspace{\cvheaderoffset mm}%
    \begin{minipage}{\dimexpr(\linewidth + \timelinespace mm - \cvavatarradius mm - \cvheaderoffset mm)}%
        \huge{#3}%   <- HERE
        \cvseparator[2]%
        \Large{#4}%   <- HERE 
    \end{minipage}%
    
    \columnratio{\cvcolumnratio}%
    
    \begin{paracol}{2}%
}{%
    \end{paracol}%
}%
```

I had to modify 3 lines. I don't know why there was an error for the text scaling function after changing the avatar shape. When I used \huge and \Large instead, it started working. Checkout if you get the desired result.

**Comment by eyildiz-ugoe** [comment]
It did work, thanks for the rapid response! :)
