### ISSUE TITLE
Icons Appear Black Instead of White in PDF Conversion

### ISSUE THREAD

**Issue by ludvigjh** [mateuszbaransanok/BubbleCV#3]
When attempting to convert the template to PDF, the icons within the template appear in black, despite having the icon color parameter set to white. While the icons display as white in the Overleaf preview, this issue arises specifically during the PDF conversion process.

**Comment by mateuszbaransanok** [comment]
Hi, I never had problem before like this. What compiler and Tex live version are you using? Does the problem still occur if you change PDF viewer to `Browser`? Are you trying to export to PDF vanilla template or after some mortification?

**Comment by luudvigjh** [comment]
The compiler I am using is pdfLaTeX, and the TeX Live version is 2021. When the PDF viewer is set to Overleaf, the symbols appear in white. However, when I switch to the browser view, the symbols turn black. I have tried exporting a raw template, but the result remains unchanged.

**Comment by ludvigjh** [comment]
The compiler I am using is pdfLaTeX, and the TeX Live version is 2021. When the PDF viewer is set to Overleaf, the symbols appear in white. However, when I switch to the browser view, the symbols turn black. I have tried exporting a raw template, but the result remains unchanged.
<img width="922" alt="Skjermbilde 2023-08-11 kl  17 14 27" src="https://github.com/mateuszbaransanok/BubbleCV/assets/111861438/745e5b8f-060e-4b5f-b4d2-add2e17f1c5d">

**Comment by mateuszbaransanok** [comment]
Unfortunately, I can't reproduce your problem. If it is a problem with re-coloring black mask icons, you can try replacing the existing black icons in `/resources` with white icons (you can use any image editor to do this).

**Comment by GiacomoRosato** [comment]
@mateuszbaransanok How is that possible? The template is on Overleaf, it's quite straightforward to reproduce it. Btw, even inverting the colours, the result is the same.

**Comment by mateuszbaransanok** [comment]
My point is that for me and other people I know, the template works perfectly fine. Maybe try with another browser, another PDF program? I honestly don't know what could be causing this problem, as it works fine with me.

**Comment by GiacomoRosato** [comment]
Ok, so can you please give me your set up to make it work? (browser, PDF program, compiler and Tex live version etc)

**Comment by mateuszbaransanok** [comment]
Sure, 

System: Linux Ubuntu 22.04
Browser: Google Chrome Version 115.0.5790.170 (Official Build) (64-bit)
PDF program: Document Viewer 42.3
Compiler: pdfLaTeX
Tex live version: 2023

Could you give me your parameters? I will also try to reproduce it using your settings.

**Comment by hoffmka** [comment]
I had the same problem. It seems that the problem is caused by the pdf viewer "Vorschau" on macOS. Adobe shows everything fine. Thank you, @mateuszbaransanok! It's a nice and concise CV.

**Comment by mateuszbaransanok** [comment]
Thank you for letting me know about this problem. I will investigate it and try to fix it. 

I'm very glad you like the template :D I'd appreciate it if you join [Stargazers](https://github.com/mateuszbaransanok/BubbleCV/stargazers) by clicking the star at this project ;) it will really help me. Thanks in advance! :D

**Comment by GiacomoRosato** [comment]
As @hoffmka said, I finally realised the problem is the "Preview" app to read the PDF. By changing it, everything works as expected. Thank you for your help and the design of this template :)

**Comment by 679394277** [comment]
Hello, this template is very nice and concise.  However, I have issues changing the James Bond avatar . I wish replace that with another image or better still remove it. How can I go about that? 
Thank you

**Comment by 679394277** [comment]
I equally wish to modify the icon colors from black to cyan. Please I need help
Thank you

**Comment by mateuszbaransanok** [comment]
Hi, the template was designed with an image. If you don't want it, you can replace it with some nice image. Simply replace the image with `resources/avatar.png` or add a new one with a custom name, then provide it to `begin{cv}[custom-name]{James Bond}{Secret Agent}`.
There is also a way to remove the image by setting this parameter in the `bubblecv.sty` file as follows:
```
\newcommand\cvavatarradius{10}
\newcommand\cvavatarborderwidth{10}
\newcommand\cvheaderoffset{0}
``` 
but in my opinion the resume looks worse.
To change the colors of the bubbles, just set the main color of the resume with `\definecolor{cvcolor}{RGB}{0, 255, 255}`  (the cyan color in RGB is {0, 255, 255}). I recommend choosing darker colors to contrast more with the white paper ;) .

**Comment by 679394277** [comment]
Thank you for your reply. Great template.
Keep up the good work

**Comment by martinzillmer** [comment]
Hope [this](https://github.com/mateuszbaransanok/BubbleCV/issues/8#issuecomment-1827849950) reply can help.

**Comment by DerCarlauer** [comment]
The template is really great. Thanks for creating it @mateuszbaransanok. Could you please open this issue again?
The above solution does not seem to work.

A CV is used for job applications and therefore it should look as desired in any setup. You don't know which PDF viewer the potential employer is using. And asking them to use a specific PDF viewer seems quite unprofessional to me.
So it would be great if we could find a fix here so that the work you put into your CV before realising the above issue is not in vain.

**Comment by martinzillmer** [comment]
If you want to use the default black/white color scheme, and easy workaround is to change line 218 in the bubblecv.sty to

decodearray={1 0 1 0 1 0}]{#1}%

from

 decodearray={\customdecodearray}]{#1}%

Essentially, the colours of the pictures in the resources folder need to be inverted, and the decode array value of {1 0 1 0 1 0} takes the negative of the r, g, and b colors (though other decode arrays can be explored, using decimal values between 0 and 1).

That solved the issue for me at least, so i hope it will do the same for you.

**Comment by mateuszbaransanok** [comment]
Hi @DerCarlauer,  sorry you had to wait so long. I bought my first MacBook a few days ago, so I am finally able to take a closer look at the issue. 

The problem is not trivial and lies in the `decodearray` argument of `includegraphics` function.
I'm afraid there's nothing I can do, because apparently not every PDF reader supports color mapping like the one in macOS.

I agree that by default the template should work on any pdf reader, so I will set the icons to white as originally intended.
To change the color of the icons, use a proper tool such as GIMP. 

That's all I can help for now, but I will continue to look for a solution. Keep a cross fingers ;)
