### ISSUE TITLE
Icon color not properly rendered in mac

### ISSUE THREAD

**Issue by weixinli018** [mateuszbaransanok/BubbleCV#8]
Hi, I just noticed that the color of the icon for cvsection is not properly rendered for some reason. It is supposed to be black background and white foreground by default, but both turn out dark in the pdf generated in my case (macbook pro). Does anyone have this problem? 

<img width="1165" alt="image" src="https://github.com/mateuszbaransanok/BubbleCV/assets/9374260/9bab3570-7ead-4353-9f9c-06d1bb6ebbcb">

**Comment by mateuszbaransanok** [comment]
Workaround is here https://github.com/mateuszbaransanok/BubbleCV/issues/3#issuecomment-1732389230 . I haven't yet dealt with this issue.

**Comment by martinzillmer** [comment]
This is not an issue with mac as such, but an issure with the Preview PDF viewer. Using Adobe Acrobate Reader or a browser does not show this issue for me at least. 

If you want to use the default black/white color scheme, and easy workaround is to change line 218 in the bubblecv.sty to 

`decodearray={1 0 1 0 1 0}]{#1}%`

from

` decodearray={\customdecodearray}]{#1}%`

Essentially, the colours of the pictures in the resources folder need to be inverted, and the decode array value of {1 0 1 0 1 0} takes the negative of the r, g, and b colors (though other decode arrays can be explored, using decimal values between 0 and 1).

That solved the issue for me at least, so i hope it will do the same for you.
