### ISSUE TITLE
Black circles instead of section icons

### ISSUE THREAD

**Issue by jasminWohlrab** [mateuszbaransanok/BubbleCV#9]
Hello, 

I'm having problems with the cvsection. In Overleaf and in my local TexStudio installation on my Mac, everything looks as desired in the PDF preview. However, in the generated PDF file main.pdf, the section icons are not displayed in the cvsection, but only black circles are output. What could that be about?

Best regards,
Jasmin

**Comment by mateuszbaransanok** [comment]
Workaround is [here](https://github.com/mateuszbaransanok/BubbleCV/issues/3#issuecomment-1732389230). I haven't yet dealt with this issue.
